ignore_merge_commits = false
branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = ["git push", "git push {{version}}"]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[commit_types]
hotfix = { changelog_title = "Hotfixes" }
release = { changelog_title = "Releases" }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "nvim"
owner = "sRavioli"
authors = [{ username = "sRavioli", signature = "Simone Fidanza" }]

# [bump_profiles]

# [packages]
