---
name: ci
run-name: Perform release from latest tag

on:
  push:
    branches: [main]

jobs:
  release:
    name: Create a GitHub release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SemVer release
        uses: cocogitto/cocogitto-action@v3.5
        id: relase
        with:
          check-latest-tag-only: true
          release: true

      - name: Generate changelog
        run: >-
          cog changelog --at ${{ steps.release.outputs.version }} --template
          remote > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
