---
name: ci
run-name: Perform release from latest tag

on: [push]

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: Create release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          release: true

      - name: Generate Changelog
        run: >-
          cog changelog --at ${{ steps.release.outputs.version }} -t remote  --remote
          github.com --owner sRavioli --repository nvim > GITHUB_CHANGELOG.md

      - name: Print version
        run: echo '${{ steps.release.outputs.version }}'

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
